application: picture-counter
version: 1
runtime: go
api_version: go1

handlers:
  - url: /(.*\.html)$
    static_files: html/\1
    upload: html/.*\.html$

  - url: /$
    static_files: html/index.html
    upload: html/index.html$

  - url: /js/(.*\.js)$
    static_files: html/js/\1
    upload: html/js/.*\.js$

  - url: /style/(.*\.css)$
    static_files: html/style/\1
    upload: html/style/.*\.js$

  - url: /.*
    script: _go_app
